name: ðŸ› Bug Report
description: Create a report to help us improve Sonant.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        # ðŸ›‘ STOP AND READ
        **Before you submit:**
        1. Verify `AudioModulation` and `GameplayTags` plugins are enabled.
        2. Ensure `DA_Sonant_Global` is assigned in **Project Settings > Game > Sonant**.
        3. If this is a Build Error, ensure you are testing on a clean project.

  - type: checkboxes
    id: firewall
    attributes:
      label: Pre-Submission Checklist (The Firewall)
      description: If you do not check these, your issue will be closed immediately.
      options:
        - label: I am using Unreal Engine 5.7 or higher. (Sonant is 5.7+ only).
          required: true
        - label: I have verified that the 'Sonant Config' is assigned in Project Settings.
          required: true
        - label: I have cleaned my `Intermediate` and `Binaries` folders and rebuilt.
          required: true
        - label: I have tested this behavior in a new, empty Map to rule out level-specific corruption.
          required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Problem Category
      options:
        - "Surface Resolution (Footsteps/Impacts)"
        - "Atmosphere Mixer (Priority Stack)"
        - "Compilation / Build Error"
        - "Crash (CTD)"
    validations:
      required: true

  - type: input
    id: material-string
    attributes:
      label: The "Input" String
      description: What is the EXACT name of the Material/MaterialInstance you are walking on?
      placeholder: e.g. M_Temple_Stone_Wet_01
    validations:
      required: true

  - type: input
    id: config-key
    attributes:
      label: The "Config" Key
      description: What Keyword do you have mapped in SonantConfig?
      placeholder: e.g. Stone
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Expected vs Actual Behavior
      description: Don't tell us "it doesn't work". Tell us "I walked on X, I expected sound Y, but I got Z (or Silence)."
      placeholder: |
        Expected: Hearing 'S_Stone_Impact' when walking on the temple floor.
        Actual: Default fallback sound played (or silence).
    validations:
      required: true

  - type: textarea
    id: debug-overlay
    attributes:
      label: Debug Overlay Data
      description: What does the Sonant Debug Overlay say? (Use console command `SonantDebug 1` if implemented, or check Output Log).
      placeholder: |
        Active Mix: Audio.Zone.Forest
        Active Count: 1
        Priority: 5
    validations:
      required: false

  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior in a CLEAN project.
      placeholder: |
        1. Create new UE 5.7 project.
        2. Enable Sonant.
        3. Map "Test" to a Sound in config.
        4. Name a Material "M_Test".
        5. Call PlayFootstep via Blueprint.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Output Log / Callstack
      description: Paste the crash callstack or the Output Log showing Sonant initialization. Use code blocks.
      render: shell
    validations:
      required: false

  - type: dropdown
    id: build-type
    attributes:
      label: Build Environment
      options:
        - "Unity Build (Default)"
        - "Non-Unity / Strict (bUseUnity=false)"
        - "Packaged Build (Shipping)"
        - "Packaged Build (Development)"
    validations:
      required: true
